CREATE WAREHOUSE ENERGY_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE DATABASE ENERGY_ANALYTICS;

USE DATABASE ENERGY_ANALYTICS;

CREATE SCHEMA ENERGY_SCHEMA;

USE SCHEMA ENERGY_SCHEMA;

SHOW DATABASES;
SHOW SCHEMAS;
SHOW WAREHOUSES;