USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE ENERGY_ANALYTICS;
USE SCHEMA ENERGY_SCHEMA;

CREATE OR REPLACE TABLE DIM_OIL_TYPE (
    TYPE_ID INTEGER PRIMARY KEY,
    OIL_TYPE STRING
);

CREATE OR REPLACE TABLE DIM_DATE (
    DATE DATE PRIMARY KEY,
    YEAR INTEGER,
    MONTH INTEGER,
    QUARTER INTEGER
);

CREATE OR REPLACE TABLE FACT_OIL_PRODUCTION (
    DATE DATE,
    TYPE_ID INTEGER,
    PRODUCTION_VOLUME FLOAT,
    FOREIGN KEY (DATE) REFERENCES DIM_DATE(DATE),
    FOREIGN KEY (TYPE_ID) REFERENCES DIM_OIL_TYPE(TYPE_ID)
);

show tables;

describe table DIM_OIL_TYPE;

SELECT * FROM DIM_OIL_TYPE;

SELECT SUM(PRODUCTION_VOLUME)
FROM FACT_OIL_PRODUCTION;

